name: C/C++ CI

on:
  push:
    branches: [ "master", "next" ]
  pull_request:
    branches: [ "master", "next" ]

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v4
    - name: cmake
      run: cmake -GNinja . -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=On -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -Wall -Wextra -Wpedantic -Wmisleading-indentation -Wunused -Wuninitialized -Wshadow -Wconversion -Werror"
    - name: ninja
      run: ninja
    - name: ninja test
      run: ninja test


  #macos:

  #  runs-on: macos-latest

  #  steps:
  #  - uses: actions/checkout@v3
  #  - name: Install ninja-build tool
  #    uses: seanmiddleditch/gha-setup-ninja@v4
  #  - name: cmake
  #    run: cmake -GNinja . -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=On -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -Wall -Wextra -Wpedantic -Wmisleading-indentation -Wunused -Wuninitialized -Wshadow -Wconversion -Werror"
  #  - name: ninja
  #    run: ninja
  #  - name: ninja test
  #    run: ninja test

